### ISSUE TITLE
Support for python 3.7.2

### ISSUE THREAD

**Issue by yppgeorge** [changyuheng/pywinwifi#2]
Print commands in the module are throwing up errors as below. 
Guess the python version(3.7.2) i am using from the one that the code is developed on. 
`Traceback (most recent call last):
  File "E:/G_InternetOfThings/Wi-Fi/HomeStatusChecker.py", line 1, in <module>
    import pywinwifi
  File "E:\G_InternetOfThings\venv\lib\site-packages\pywinwifi\__init__.py", line 1, in <module>
    from .pywinwifi import *
  File "E:\G_InternetOfThings\venv\lib\site-packages\pywinwifi\pywinwifi.py", line 42
    print "Total interfaces available: %s"  %totalInterfaces
                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Total interfaces available: %s"  %totalInterfaces)?

Process finished with exit code 1
`

**Comment by johannjhang** [comment]
Hi @yppgeorge, you raised an issue in the wrong place. I think you meant to go here: https://pypi.org/project/pywinwifi/

Feel free to give a try to `winwifi.py` as well!
